version: 2
workflows:
  version: 2
  workflow:
    jobs:
      - unit-tests
      - lint
      - meta-lint
jobs:
  unit-tests:
    docker:
      - image: golang:1.13
    steps:
      - checkout
      - run:
          name: Run unit tests.
          command: go test -mod=readonly -v ./...
  lint:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run:
          name: Install golangci-lint
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
      - run:
          name: Run golangci-lint
          command: "! $(go env GOPATH)/bin/golangci-lint run ./... 2>&1 | read"
      - run:
          name: Check Format
          command: "! go fmt ./... 2>&1 | read"
  meta-lint:
    docker:
      - image: golang:1.13-alpine
    steps:
      - checkout
      - run:
          name: Run the meta-linter, ensuring in-repository consistency.
          command: go run ./.circleci/meta-linter
